version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules

  nginx:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "81:81"
    
    depends_on:
      - app